name: Deploy Automático

on:
  push:
    branches: ["master"] # Alterado para 'main' (ou mantenha 'master' se for seu caso)
    paths:
      - "**" # Monitora todas as alterações no repositório

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build -- --configuration=production

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          echo "Host willians-vps" > ~/.ssh/config
          echo "  HostName ${{ secrets.SERVER_IP }}" >> ~/.ssh/config
          echo "  User ${{ secrets.DEPLOY_USER }}" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/deploy_key" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

          echo "Conteúdo do arquivo config:"
          cat ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Test SSH connection
        run: ssh -T willians-vps echo "SSH connection successful!"

      - name: Deploy files
        run: |
          ssh willians-vps "mkdir -p /var/www/projects/frontend/willians-invest"
          scp -r dist/willians-invest-web/* willians-vps:/var/www/projects/frontend/willians-invest/

      - name: Fix permissions
        run: |
          ssh willians-vps "sudo chown -R www-data:www-data /var/www/projects/frontend/willians-invest"
          ssh willians-vps "sudo systemctl restart nginx"
