name: Deploy Automático

on:
  push:
    branches: ["master"] # Alterado para 'main' (ou mantenha 'master' se for seu caso)
    paths:
      - "**" # Monitora todas as alterações no repositório

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build -- --configuration=production

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Enviar arquivos via SCP
        run: |
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -r dist/willians-invest/* root@89.116.73.70:${{ steps.project.outputs.dest_dir }}

      - name: Fix permissions
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} "sudo chown -R www-data:www-data /var/www/projects/frontend/willians-invest"
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_IP }} "sudo systemctl restart nginx"
